### ISSUE TITLE
Algorithm does not terminate

### ISSUE THREAD

**Issue by PySlu** [z80z80z80/autocrop#2]
My scanner produces images like the attached example. The algorithm does not terminate with the attached file.
![test](https://user-images.githubusercontent.com/6278380/97700906-dc70a900-1aac-11eb-8d39-ac26aab717b1.png)

**Comment by z80z80z80** [comment]
Thanks for this edge case, seems like I made some mistakes while refactoring the code recently. I addressed the issue with commits https://github.com/z80z80z80/autocrop/commit/0c76bc06df7276a6440666793bc6d1145e22e6d8 and https://github.com/z80z80z80/autocrop/commit/abb6d7d4a540ad5594d370e95d77597e2eaef9a7.

However, this doesn't solve this particular case, which comes down to the composition of your scan. The algorithm assumes an uniform background with the subject being darker than the background. 

My suggestions:
-  figure out why your scanner is messing the background up like this and make it an uniform background that makes it easy to differentiate it from the parking ticket. For example, use a dark sheet of paper that's on top of the ticket (for a simulated example have a look at the attached image). If you can't get your scanner to behave, you can also take a picture of the ticket with a similar technique.
- invert the image to make sure the subject is brighter than the background, `convert input.png -negate negative.png`
- `python autocrop.py -i negative.png -s -t 100` (you might have to fiddle with the threshold in this scenario)
- `convert crop/negative.png -negate crop/input.png`

![input](https://user-images.githubusercontent.com/59485146/97727376-9dece580-1ad0-11eb-9e01-7021c6bcb1b5.png)

**Comment by PySlu** [comment]
Thank you for the fast reply! I'll check out your suggestions.

**Comment by z80z80z80** [comment]
FYI: My latest commit might be helpful for the inverting steps in my suggestions https://github.com/z80z80z80/autocrop/commit/a49f66c1551047e4328d02960a599ded4fcdd049. 

Just add `-b` after preparing your scan as suggested be before :)
