### ISSUE TITLE
One closing bracket missing

### ISSUE THREAD

**Issue by bjoerm** [z80z80z80/autocrop#3]
Hey,
Thanks a lot for your this code!

I noted that one bracket is not being closed on line 114 currently:
https://github.com/z80z80z80/autocrop/blob/abb6d7d4a540ad5594d370e95d77597e2eaef9a7/autocrop.py#L114

should be
`print("WARNING: This seems to be an edge case. If the result isn't satisfying try lowering the threshold using -t")`

Cheers.

**Comment by z80z80z80** [comment]
Thank you! Fixed in https://github.com/z80z80z80/autocrop/commit/7f12c0ad50b06e7cc2f75484eecac0040608252e.
