### ISSUE TITLE
Enormous post-conversion file size

### ISSUE THREAD

**Issue by tbhsm** [z80z80z80/autocrop#7]
Found your script useful for a similar issue I'm running into for photo scans. It works well for me, but the file size increases significantly. E.g. uncropped, my images are 300-500kB but cropped they are about 1.5-2.5MB. Any idea why this is happening?

**Comment by tbhsm** [comment]
Solved by changing the quality level on line 154. Maybe add a output quality argument? Or better yet, alter this dynamically to match the input picture quality? :)

**Comment by fcoiffie** [comment]
I added an argument to change the JPEG quality in my version: https://github.com/fcoiffie/autocrop (set to 92 by default)
