### ISSUE TITLE
Script error - syntax error

### ISSUE THREAD

**Issue by LM723** [z80z80z80/autocrop#8]
Hi
I am trying to run the script, but it gives me an error:

python autocrop.py

  File "autocrop.py", line 87
    print(f"Adjust Threshold: {user_thresh}")
                                           ^
SyntaxError: invalid syntax

What could be the problem?

**Comment by Stoiker** [comment]
Hi, what python version are you using?

**Comment by LM723** [comment]
Python 2.7.18

**Comment by LM723** [comment]
Argh.... solved. I haven't realized that there was a phyton 3. It was installed but not default. So running "phython3 autocrop.py" worked.

**Comment by Stoiker** [comment]
Great that it works now; I think we can close this issue.
